### ISSUE TITLE
Dependency `superagent-use` fails installation.

### ISSUE THREAD

**Issue by Alexintosh** [ElementsProject/lightning-charge-client-js#1]
Looks like the `shesek/superagent-use` it's breaking the installation process.

**Comment by shesek** [comment]
What error are you getting?

**Comment by shesek** [comment]
@Alexintosh were you able to resolve this?

**Comment by Alexintosh** [comment]
I couldn't, this is the full log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/alexintosh/.nvm/versions/node/v8.1.2/bin/node',
1 verbose cli   '/Users/alexintosh/.nvm/versions/node/v8.1.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   'lightning-charge-client' ]
2 info using npm@5.6.0
3 info using node@v8.1.2
4 verbose npm-session ad9f41bd1da4b4a9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/lightning-charge-client 408ms (from cache)
8 silly pacote tag manifest for lightning-charge-client@latest fetched in 473ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly pacote git manifest for lightning-charge-client@git+https://github.com/Alexintosh/lightning-charge-client-js.git#14f6acbd1d10a57e708717c694ac66e7b46106e9 fetched in 483ms
13 silly install loadAllDepsIntoIdealTree
14 silly resolveWithNewModule lightning-charge-client@0.1.4 checking installable status
15 http fetch GET 304 https://registry.npmjs.org/superagent-baseuri 246ms (from cache)
16 silly pacote range manifest for superagent-baseuri@^0.1.1 fetched in 251ms
17 silly resolveWithNewModule superagent-baseuri@0.1.1 checking installable status
18 silly fetchPackageMetaData error for superagent-use@git://github.com/shesek/superagent-use.git#patch-1 Error while executing:
18 silly fetchPackageMetaData /usr/local/bin/git ls-remote -h -t git://github.com/shesek/superagent-use.git
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData fatal: unable to connect to github.com:
18 silly fetchPackageMetaData github.com[0: 192.30.253.112]: errno=Operation timed out
18 silly fetchPackageMetaData github.com[1: 192.30.253.113]: errno=Operation timed out
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData exited with error code: 128
19 silly saveTree lightning-test@1.0.0
19 silly saveTree └─┬ lightning-charge-client@0.1.4
19 silly saveTree   ├─┬ superagent-baseuri@0.1.1
19 silly saveTree   │ └── superagent-prefix@0.0.2
19 silly saveTree   └─┬ superagent@3.8.2
19 silly saveTree     ├── component-emitter@1.2.1
19 silly saveTree     ├── cookiejar@2.1.1
19 silly saveTree     ├─┬ debug@3.1.0
19 silly saveTree     │ └── ms@2.0.0
19 silly saveTree     ├── extend@3.0.1
19 silly saveTree     ├─┬ form-data@2.3.1
19 silly saveTree     │ ├── asynckit@0.4.0
19 silly saveTree     │ ├─┬ combined-stream@1.0.5
19 silly saveTree     │ │ └── delayed-stream@1.0.0
19 silly saveTree     │ └─┬ mime-types@2.1.17
19 silly saveTree     │   └── mime-db@1.30.0
19 silly saveTree     ├── formidable@1.1.1
19 silly saveTree     ├── methods@1.1.2
19 silly saveTree     ├── mime@1.6.0
19 silly saveTree     ├── qs@6.5.1
19 silly saveTree     └─┬ readable-stream@2.3.3
19 silly saveTree       ├── core-util-is@1.0.2
19 silly saveTree       ├── inherits@2.0.3
19 silly saveTree       ├── isarray@1.0.0
19 silly saveTree       ├── process-nextick-args@1.0.7
19 silly saveTree       ├── safe-buffer@5.1.1
19 silly saveTree       ├── string_decoder@1.0.3
19 silly saveTree       └── util-deprecate@1.0.2
20 verbose stack Error: exited with error code: 128
20 verbose stack     at ChildProcess.onexit (/Users/alexintosh/.nvm/versions/node/v8.1.2/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
20 verbose stack     at emitTwo (events.js:125:13)
20 verbose stack     at ChildProcess.emit (events.js:213:7)
20 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
21 verbose cwd /Users/alexintosh/Code/kairos/LIGHTNING/demo-app
22 verbose Darwin 16.7.0
23 verbose argv "/Users/alexintosh/.nvm/versions/node/v8.1.2/bin/node" "/Users/alexintosh/.nvm/versions/node/v8.1.2/bin/npm" "install" "lightning-charge-client"
24 verbose node v8.1.2
25 verbose npm  v5.6.0
26 error Error while executing:
26 error /usr/local/bin/git ls-remote -h -t git://github.com/shesek/superagent-use.git
26 error
26 error fatal: unable to connect to github.com:
26 error github.com[0: 192.30.253.112]: errno=Operation timed out
26 error github.com[1: 192.30.253.113]: errno=Operation timed out
26 error
26 error
26 error exited with error code: 128
27 verbose exit [ 1, true ]
```

**Comment by shesek** [comment]
@Alexintosh This appears to be an internet connectivity issue, your npm client is for some reason unable to pull code from github (but can pull from the npm registry, it seems).

The reason it tries to pull code from github is that `superagent-baseuri` [depends on](https://github.com/shesek/superagent-baseuri/blob/e3ddd164ca69c995fd88d7627c22146e92c15459/package.json#L12) a [modified copy](https://github.com/shesek/superagent-use/commit/3a8d0d2dd25b9912cdc581e7c5e65ccf4ab4e657) of `superagent-use` that only exists on github and not on npm. I sent a [PR](https://github.com/koenpunt/superagent-use/pull/6) to get these changes merged upstream, so that they'll be available from the npm registry directly.

Note that this doesn't explain why your client is unable to connect to github... if you can figure this out, you should be able to use `lightning-charge-client-js` as-is. But in any case, I'll keep you updated about getting these changes available on npm.

**Comment by Alexintosh** [comment]
@shesek I can pull dependencies and code from whatever github repo besides `git://github.com/shesek/superagent-use.git`. It is an issue specifically to that repo, tried with different internet connection and different machine already.

**Comment by shesek** [comment]
Are you still experiencing this issue? I'm unable to reproduce this and haven't heard about anyone else running into this.

**Comment by Alexintosh** [comment]
Hey @shesek thanks for asking again, looks like the issue solved itself somehow, now sure what happened tho. Wil close the issue, thanks!
